####################################################################################################
#####                              TX Ultimate Easy for ESPHome                                #####
#####                  Repository: https://github.com/edwardtfn/TX-Ultimate-Easy               #####
####################################################################################################
##### Author: edwardtfn - https://github.com/edwardtfn - https://buymeacoffee.com/edwardfirmo  #####
####################################################################################################
---
substitutions:
  name: tx-ultimate-easy
  friendly_name: TX Ultimate Easy
  device_format: EU  # REQUIRED: 'EU' or 'US' (case-sensitive, uppercase only)
  gang_count: 1      # REQUIRED: Number of relays/buttons (1, 2, 3, or 4)

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

packages:
  # yamllint disable rule:colons
  core:     !include ESPHome/TX-Ultimate-Easy-ESPHome_core.yaml
  standard: !include ESPHome/TX-Ultimate-Easy-ESPHome_standard.yaml
  # - ESPHome/TX-Ultimate-Easy-ESPHome_addon_ble_proxy.yaml        # Adds BLE proxy support
  # yamllint enable rule:colons
...
